#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton --respect-prop-shadow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap					 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc rule -a albert:albert border=off

/usr/bin/env ~/.config/polybar/launch.sh &
dunst &
# mpd &
feh --bg-center --bg-max ~/Pictures/background.jpg &
setxkbmap -layout us,ru,ua -option "grp:alt_shift_toggle" &
xsetroot -cursor_name left_ptr
telegram-desktop -startintray &
# wmname compiz
# export AWT_TOOLKIT=MToolkit
# export _JAVA_AWT_WM_NONREPARENTING=1
# sh ~/java-script.sh
