#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a albert:albert border=off

sh ~/.config/polybar/launch.sh --forest &
dunst &
mpd &
feh --bg-center ~/Documents/ddee216-a189d515-4ad6-45d0-baec-8315d3184348.png &
setxkbmap -layout us,ru,ua -option "grp:alt_shift_toggle" &
telegram-desktop -startintray &
# wmname compiz
# export AWT_TOOLKIT=MToolkit
# export _JAVA_AWT_WM_NONREPARENTING=1
# sh ~/java-script.sh
